---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: enp3s0-enable-noip
spec:
  nodeSelector:
    # ovn.ext-gw.example.org/frr-pod: ""
    kubernetes.io/hostname: w1
  desiredState:
    interfaces:
    - name: enp3s0
      type: ethernet
      state: up
      ipv4:
        dhcp: false
        enabled: false

# oc get nncp
# oc label node w1 ovn.ext-gw.example.org/frr-pod=""
# vlan 11