---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-configs
data:
  daemons: |
    bgpd=no
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=yes
    fabricd=no
    vrrpd=no
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1"
    ospfd_options="  -A 127.0.0.1"
    ospf6d_options=" -A ::1"
    ripd_options="   -A 127.0.0.1"
    ripngd_options=" -A ::1"
    isisd_options="  -A 127.0.0.1"
    pimd_options="   -A 127.0.0.1"
    ldpd_options="   -A 127.0.0.1"
    nhrpd_options="  -A 127.0.0.1"
    eigrpd_options=" -A 127.0.0.1"
    babeld_options=" -A 127.0.0.1"
    sharpd_options=" -A 127.0.0.1"
    pbrd_options="   -A 127.0.0.1"
    staticd_options="-A 127.0.0.1"
    bfdd_options="   -A 127.0.0.1"
    fabricd_options="-A 127.0.0.1"
    vrrpd_options="  -A 127.0.0.1"
  frr.conf: |
    password frr
    enable password frr
    bfd
     peer 192.168.216.14 interface net1
       no shutdown
       debug bfd network
       debug bfd peer
       debug bfd zebra
     !
    !
    bfd
     peer 192.168.216.15 interface net1
       no shutdown
       debug bfd network
       debug bfd peer
       debug bfd zebra
     !
    !
    # log file /var/log/frr/frr.log debugging
    log file /tmp/frr.log debugging
    #log stdout debugging
  bfdd.conf: ""
  bgpd.conf: ""
  ospf6d.conf: ""
  ospfd.conf: ""
  pbrd.conf: ""
  staticd.conf: ""
  vtysh.conf: |
    no service integrated-vtysh-config
  zebra.conf: |
    hostname vrouter
